# version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8081:80"
    depends_on:
      - db:
    command: uvicorn app.main:app --host 0.0.0.0 --port 80

volumes:
  postgres_data: